[dep] upgrade uship, fusion, tomcat and commons-compress
yupiik/yupiik-batch pull request #12
Opened 2024-11-25 13:25 UTC by mxfo

2024-11-25 13:31 UTC, fpapon requested changes

2024-11-25 13:31 UTC, fpapon commented on pom.xml
> +        <version>2.18.0</version>
It could be nice to use a property for the commons-io version.

2024-11-26 04:51 UTC, mxfo commented on pom.xml
> +        <version>2.18.0</version>
Done with properties for version of commons-compress, commons-io and h2

2024-11-26 08:34 UTC, fpapon approved these changes
LGTM!

2024-11-26 08:34 UTC, merged